# Filler text
version: '3'
services:

  node:
    container_name: recipe-node-app
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    volumes:
      - ".:/app"
      - "/app/node_modules"

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network
    # Below is for testing from host machine and not just node container
    ports:
      - "27017:27017"

networks:
  nodeapp-network:
    driver: bridge
