# Filler text
version: '3'
services:

  node:
    container_name: recipe-api
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - recipe-app-network
    volumes:
      - ".:/app"
      - "/app/node_modules"

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - recipe-app-network
    # Below is for testing from host machine and not just node container
    ports:
      - "27017:27017"

networks:
  recipe-app-network:
    driver: bridge
